<a href="https://colab.research.google.com/github/akshatsoni64/DataMining/blob/master/LinearAlgebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
x=np.matrix("4,5,16,7,;2,-3,2,3;3,4,5,6;4,7,8,9")
print(x)

[[ 4  5 16  7]
 [ 2 -3  2  3]
 [ 3  4  5  6]
 [ 4  7  8  9]]


In [0]:
detmat=np.linalg.det(x)
print(detmat)

128.00000000000009


In [0]:
rank=np.linalg.matrix_rank(x)
print(rank)

4


In [0]:
a=np.matrix("3,1,2;3,2,5;6,7,8")
print(a)
inv=np.linalg.inv(a)
print(inv)

[[3 1 2]
 [3 2 5]
 [6 7 8]]
[[ 0.57575758 -0.18181818 -0.03030303]
 [-0.18181818 -0.36363636  0.27272727]
 [-0.27272727  0.45454545 -0.09090909]]


In [0]:
b=np.matrix("2,1,2;1,0,1;3,1,3")
print(b)
det=np.linalg.det(b)
print(det)

[[2 1 2]
 [1 0 1]
 [3 1 3]]
0.0


In [0]:
y=np.matrix("2,-1,3").transpose()
print(np.linalg.solve(a,y))

[[ 1.24242424]
 [ 0.81818182]
 [-1.27272727]]
