<a href="https://colab.research.google.com/github/akshatsoni64/DataMining/blob/master/Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
mt=np.matrix("1,2,3,4;4,5,6,7;7,8,9,10")
print(mt)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [0]:
print(mt.shape)

(3, 3)


In [0]:
print("Cols:",mt.shape[1])

Cols: 4


In [0]:
print(mt.size)

12


In [0]:
col_new=np.matrix("2,3,4")
print(col_new)

[[2 3 4]]


In [0]:
mt=np.insert(mt,0,col_new,axis=1)
print(mt)

[[ 2  1  2  3  4]
 [ 3  4  5  6  7]
 [ 4  7  8  9 10]]


In [0]:
row_new=np.matrix("4,5,6,7,9")
print(row_new)

[[4 5 6 7 9]]


In [0]:
mt=np.insert(mt,0,row_new,axis=0)
print(mt)

[[ 4  5  6  7  9]
 [ 4  5  6  7  9]
 [ 2  1  2  3  4]
 [ 3  4  5  6  7]
 [ 4  7  8  9 10]]


In [0]:
mt[1,1]=-3
print(mt)

[[ 4  5  6  7  9]
 [ 4 -3  6  7  9]
 [ 2  1  2  3  4]
 [ 3  4  5  6  7]
 [ 4  7  8  9 10]]


In [0]:
print(mt[:,2])

[[6]
 [6]
 [2]
 [5]
 [8]]


In [0]:
print(mt[1,2])

6


In [0]:
A=np.matrix(np.arange(0,20)).reshape(5,4)
B=np.matrix(np.arange(20,40)).reshape(5,4)
print(A)
print(B)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]


In [0]:
print(np.add(A,B))

[[20 22 24 26]
 [28 30 32 34]
 [36 38 40 42]
 [44 46 48 50]
 [52 54 56 58]]


In [0]:
print(np.subtract(A,B))

[[-20 -20 -20 -20]
 [-20 -20 -20 -20]
 [-20 -20 -20 -20]
 [-20 -20 -20 -20]
 [-20 -20 -20 -20]]


In [0]:
B=np.transpose(B)
print(np.dot(A,B))
B=np.transpose(B)

[[ 134  158  182  206  230]
 [ 478  566  654  742  830]
 [ 822  974 1126 1278 1430]
 [1166 1382 1598 1814 2030]
 [1510 1790 2070 2350 2630]]


In [0]:
print(np.multiply(A,B))

[[  0  21  44  69]
 [ 96 125 156 189]
 [224 261 300 341]
 [384 429 476 525]
 [576 629 684 741]]


In [0]:
print(np.divide(A,B))

[[0.         0.04761905 0.09090909 0.13043478]
 [0.16666667 0.2        0.23076923 0.25925926]
 [0.28571429 0.31034483 0.33333333 0.35483871]
 [0.375      0.39393939 0.41176471 0.42857143]
 [0.44444444 0.45945946 0.47368421 0.48717949]]
