<a href="https://colab.research.google.com/github/akshatsoni64/DataMining/blob/master/NumPyDemo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import sys

In [0]:
#create an array
x = np.array([2, 3, 4, 5])
print(x)

[2 3 4 5]


In [0]:
#create an array
x = np.array([2, 3, 'n', 5])
print(x)


['2' '3' 'n' '5']


In [0]:
b=np.linspace(start=1,stop=5,num=10,endpoint=True,retstep=False)
print(b)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [0]:
b=np.linspace(start=1,stop=5,num=10,endpoint=True,retstep=True)
print(b)

(array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ]), 0.4444444444444444)


In [0]:
b=np.linspace(start=1,stop=5,num=10,endpoint=False,retstep=True)
print(b)

(array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6]), 0.4)


In [0]:
d=np.arange(start=1,stop=10,step=2)
print(d)

[1 3 5 7 9]


In [0]:
d=np.ones((3,4))
print(d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [0]:
d=np.zeros((3,4),int)
print(d)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [0]:
random = np.random.rand(4)
print(random)

[0.74154425 0.73677013 0.53437378 0.93443897]


In [0]:
random = np.random.rand(4,2)
print(random)

[[0.65774628 0.73398717]
 [0.68594494 0.89166075]
 [0.57718553 0.35282742]
 [0.53969161 0.88811454]]


In [0]:
log=np.logspace(1, 10,num=5, endpoint=True, base=10.0)
print(log)

[1.00000000e+01 1.77827941e+03 3.16227766e+05 5.62341325e+07
 1.00000000e+10]


In [0]:
  sys.getsizeof(1)+len(x)

32

In [0]:
grid = np.arange(start = 1, stop = 10)
print(grid)

[1 2 3 4 5 6 7 8 9]


In [0]:
grid = np.arange(start = 1, stop = 10).reshape(3,3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [0]:
a=np.array([[1,2,3], [4,5,6],[7,8,9]])
print(a)
print("Shape: ",a.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape:  (3, 3)


In [0]:
add = np.add(grid,a)
print(add)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [0]:
mul=np.multiply(a,grid)
print(mul)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [0]:
sub=np.subtract(a,grid)
print(sub)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [0]:
div=np.divide(a,grid)
print(div)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [0]:
rem=np.remainder(a,grid)
print(rem)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [0]:
print(a[0,1])

2


In [0]:
print(a[1:3])

[[4 5 6]
 [7 8 9]]


In [0]:
print(a[:,1])

[2 5 8]


In [0]:
print(a[0,:])

[1 2 3]


In [0]:
#subset of array
a_sub=a[:2,:2]
print(a_sub)

[[1 2]
 [4 5]]


In [0]:
a_sub[0,0]=12
print(a)

[[12  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [0]:
transpose=np.transpose(a)
print(transpose)

[[12  4  7]
 [ 2  5  8]
 [ 3  6  9]]


In [0]:
a_row=np.append(a,[[10,21,24]],axis=0)
print(a_row)

[[12  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 21 24]]


In [0]:
col=np.array([12,13,14]).reshape(3,1)
print(col)

[[12]
 [13]
 [14]]


In [0]:
a_col=np.append(a,col,axis=1)
print(a)

[[12  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [0]:
a_ins=np.insert(a,1,[13,15,16],axis=0)
print(a_ins)

[[12  2  3]
 [13 15 16]
 [ 4  5  6]
 [ 7  8  9]]


In [0]:
a_del=np.delete(a_ins,2,axis=0)
print(a_del)

[[12  2  3]
 [13 15 16]
 [ 7  8  9]]
